In [5]:
cd /content/drive/MyDrive/2022/CNU/ML

[Errno 2] No such file or directory: '/content/drive/MyDrive/2022/CNU/ML'
/content


In [6]:
cd /content/drive/MyDrive/2022/CNU/ML/ML

[Errno 2] No such file or directory: '/content/drive/MyDrive/2022/CNU/ML/ML'
/content


In [7]:
!git config --global user.email '2t_hong@naver.com'
!git config --global user.name '2t_hong'

In [8]:
!git clone https://taehong-lee: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@github.com/taehong-lee/ML.git


fatal: destination path 'ML' already exists and is not an empty directory.


In [4]:
!git status

fatal: not a git repository (or any of the parent directories): .git


In [ ]:
!git add Iris.csv
!git commit -m "Connext Gooogle Colab and Drive"

[master 6772993] Connext Gooogle Colab and Drive
 1 file changed, 151 insertions(+)
 create mode 100644 Iris.csv


In [ ]:
!git add Numpy.ipynb
!git commit -m "Connext Gooogle Colab and Drive"

[master 6491f66] Connext Gooogle Colab and Drive
 1 file changed, 1 insertion(+)
 create mode 100644 Numpy.ipynb


In [ ]:
!git add Pandas.ipynb
!git commit -m "Connext Gooogle Colab and Drive"

[master afff80d] Connext Gooogle Colab and Drive
 1 file changed, 1 insertion(+)
 create mode 100644 Pandas.ipynb


In [ ]:
!git push -u origin master

Counting objects: 9, done.
Delta compression using up to 2 threads.
Compressing objects: 100% (9/9), done.
Writing objects: 100% (9/9), 12.74 KiB | 1.27 MiB/s, done.
Total 9 (delta 1), reused 0 (delta 0)
remote: Resolving deltas: 100% (1/1), done.
remote: This repository moved. Please use the new location:
remote:   https://github.com/TAEHONG-LEE/ML.git
To https://github.com/taehong-lee/ML.git
   8aba07c..afff80d  master -> master
Branch 'master' set up to track remote branch 'master' from 'origin'.


In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
import numpy as np

In [ ]:
python_list = [1, 2, 3, 4, 5]
python_list, type(python_list)

([1, 2, 3, 4, 5], list)

In [ ]:
numpy_array = np.array([1, 2, 3, 4, 5])
numpy_array, type(numpy_array)

(array([1, 2, 3, 4, 5]), numpy.ndarray)

In [ ]:
numpy_matrix = np.array([[0 for _ in range(4)] for _ in range(3)])
print(numpy_matrix.shape)
numpy_matrix

(3, 4)


array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [ ]:
numpy_zeros = np.zeros((3, 4))
print(numpy_zeros.shape)
numpy_zeros

(3, 4)


array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
numpy_tensor = np.array(
    [
        [
            [
                i for i in range(3)
            ] for _ in range(3)
        ] for _ in range(5)
    ]
)

for i, v in enumerate(numpy_tensor):
  print(i, v.shape)


print('numpy_tensor의 shape : ', numpy_tensor.shape)

0 (3, 3)
1 (3, 3)
2 (3, 3)
3 (3, 3)
4 (3, 3)
numpy_tensor의 shape :  (5, 3, 3)


In [ ]:
np_1 = np.array([1, 2, 3])
np_2 = np.array([3, 3, 3])


print(np.add(np_1, np_2))

print(np.subtract(np_2, np_1))

print(np.multiply(np_2, np_1))

print(np.divide(np_2, np_1))


[4 5 6]
[2 1 0]
[3 6 9]
[3.  1.5 1. ]


In [ ]:
product_1 = np.array([[1, 0], [0, 1]])
product_2 = np.array([[1, 2], [3, 4]])

print(np.matmul(product_1, product_2))

[[1 2]
 [3 4]]


In [ ]:
product_3 = np.array([[1, 2, 3], [3, 2], [1, 1]])
product_3

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  """Entry point for launching an IPython kernel.


array([list([1, 2, 3]), list([3, 2]), list([1, 1])], dtype=object)

In [ ]:
product_3 = np.array([[1, 2], [3, 2], [1, 1]])
product_3

array([[1, 2],
       [3, 2],
       [1, 1]])

In [ ]:
np.matmul(product_1, product_3)

ValueError: ignored

In [ ]:
product_1 @ product_3.reshape(2, 3)

array([[1, 2, 3],
       [2, 1, 1]])

In [ ]:
product_1 @ product_3.transpose()

array([[1, 3, 1],
       [2, 2, 1]])

In [ ]:
np_concat = np.concatenate((np_1, np_2))
print(np_concat, np_concat.shape)

np_transpose = np.reshape(np_concat, (2, 3))
print(np_transpose.shape)

np_t = np_transpose.transpose()
print(np_t.shape)

[1 2 3 3 3 3] (6,)
(2, 3)
(3, 2)
